### ISSUE TITLE
Muscle velocity in rigid tendon model fix

### ISSUE THREAD

**Issue by miriamfebrer** [KULeuvenNeuromechanics/MuscleRedundancySolver#32]
Now in the code we are using vMTtilde as vMtilde, and they are not equal if we consider the pennation angle.

Line 17 in HillModel_RigidTendon.m should be updated by:
vM = vMT.*cos_alpha;  % here vT = 0
vMtilde = vM./lMopt;

Line 22 should be updated by:
[FMpas,FMactFL,FMactFV] = getForceLengthVelocityProperties(lMtilde,vMtilde,vMmax);

**Comment by miriamfebrer** [comment]
@MaartenAfschrift

**Comment by mrrezaie** [comment]
https://github.com/KULeuvenNeuromechanics/MuscleRedundancySolver/blob/0325f228b90c1faef9d21a4808c3e174b0d51141/MuscleModel/HillModel/HillModel_RigidTendon.m#L17 
Hi, I'm trying to understand why the denominator here is the optimal fiber length. 
Shouldn't it be `vMtilde = (vMT / vMmax) * cos_alpha`?

Any help is greatly appreciated. Thank you in advance.

**Comment by MaartenAfschrift** [comment]
My aplogies for the slow reply @miriamfebrer .This is correct. I will change this
@mrrezaie : we divide by lMopt to normalize everything. In this implementation lMtilde = lM / lMopt and vMtilde is the time derivative of lMtilde so vMtilde = vM/lMopt. I know that this is different from the DeGroote2016 paper. In Degroote16 vMtilde is vM/(lMopt*vMax) if I remeber this correctly

**Comment by MaartenAfschrift** [comment]
@mrrezaie : if you have other questions related to the code feel free to contact me on m.a.afschrift@vu.nl. I must say that I'm not 100% up to date since the last update from Dhruv but I should be able to help you

**Comment by mrrezaie** [comment]
Thanks for the clarification. I think it belongs to Eq. 16 in that paper.
